#!/usr/bin/env bash
# Provision dedicated load-test user + webhooks on staging (one-time per env).
#
# Usage (from repo root):
#   cp deploy/deploy-aws-ecs/staging-aws.env.example deploy/deploy-aws-ecs/staging-aws.env
#   # edit STAGING_ADMIN_PASSWORD
#   ./deploy/loadtest/setup-loadtest-webhook.sh
#
# Writes deploy/loadtest/env.local with webhook tokens for each k6 scenario.

set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO="$(cd "${ROOT}/../.." && pwd)"
OUT_ENV="${LOADTEST_ENV_FILE:-${ROOT}/env.local}"

# Auto-load staging credentials + URL (same as functional/smoke runners).
if [[ -f "${REPO}/deploy/deploy-aws-ecs/staging-aws.env" ]]; then
  set -a
  # shellcheck disable=SC1091
  source "${REPO}/deploy/deploy-aws-ecs/staging-aws.env"
  set +a
fi
# shellcheck disable=SC1091
source "${REPO}/deploy/deploy-aws-ecs/scripts/common.sh"

# Reuse saved password on re-runs.
if [[ -f "${OUT_ENV}" && -z "${LOADTEST_USER_PASSWORD:-}" ]]; then
  # shellcheck disable=SC1090
  source "${OUT_ENV}"
fi

BASE_URL="${STAGING_BASE_URL:-${LOADTEST_BASE_URL:-}}"
if [[ -z "${BASE_URL}" ]]; then
  BASE_URL="$(zb_tf_output api_url)"
fi
if [[ -z "${BASE_URL}" ]]; then
  BASE_URL="https://api.staging.zettabridge.net"
  echo "NOTE: STAGING_BASE_URL unset — using default ${BASE_URL}" >&2
fi

ADMIN_EMAIL="${STAGING_ADMIN_EMAIL:-${LOADTEST_ADMIN_EMAIL:-}}"
ADMIN_PASSWORD="${STAGING_ADMIN_PASSWORD:-${LOADTEST_ADMIN_PASSWORD:-}}"
LOADTEST_EMAIL="${LOADTEST_USER_EMAIL:-loadtest@zettabridge.net}"
LOADTEST_PASSWORD="${LOADTEST_USER_PASSWORD:-loadtest-change-me-$(openssl rand -hex 8)}"
LOADTEST_SYMBOL="${LOADTEST_SYMBOL:-RELIANCE}"

CURL=(curl -4 -sS -m 60)
if [[ "${STAGING_INSECURE:-0}" == "1" ]]; then
  CURL+=( -k )
fi

if [[ -z "${ADMIN_EMAIL}" || -z "${ADMIN_PASSWORD}" ]]; then
  echo "STAGING_ADMIN_EMAIL and STAGING_ADMIN_PASSWORD are required" >&2
  exit 1
fi
BASE_URL="${BASE_URL%/}"

json_post() {
  local path="$1" token="$2" body="$3"
  local auth=()
  [[ -n "${token}" ]] && auth=( -H "Authorization: Bearer ${token}" )
  "${CURL[@]}" -X POST "${BASE_URL}${path}" \
    -H 'Content-Type: application/json' \
    "${auth[@]}" \
    -d "${body}"
}

json_put() {
  local path="$1" token="$2" body="$3"
  "${CURL[@]}" -X PUT "${BASE_URL}${path}" \
    -H 'Content-Type: application/json' \
    -H "Authorization: Bearer ${token}" \
    -d "${body}"
}

json_get() {
  local path="$1" token="$2"
  local auth=()
  [[ -n "${token}" ]] && auth=( -H "Authorization: Bearer ${token}" )
  "${CURL[@]}" "${BASE_URL}${path}" "${auth[@]}"
}

write_env_file() {
  mkdir -p "$(dirname "${OUT_ENV}")"
  cat > "${OUT_ENV}" <<EOF
# Generated by setup-loadtest-webhook.sh — do not commit
LOADTEST_BASE_URL=${BASE_URL}
LOADTEST_WEBHOOK_TOKEN=${TOKEN_MAIN}
LOADTEST_DEDUP_WEBHOOK_TOKEN=${TOKEN_DEDUP:-${TOKEN_MAIN}}
LOADTEST_RL_FREE_TOKEN=${TOKEN_RL1:-${TOKEN_MAIN}}
LOADTEST_RL_PAID_TOKEN=${TOKEN_RL10:-${TOKEN_MAIN}}
LOADTEST_BRACKET_WEBHOOK_TOKEN=${TOKEN_MAIN}
LOADTEST_USER_EMAIL=${LOADTEST_EMAIL}
LOADTEST_USER_PASSWORD=${LOADTEST_PASSWORD}
LOADTEST_USER_TOKEN=${USER_TOKEN}
LOADTEST_USER_PLAN=${LOADTEST_PLAN}
LOADTEST_WEBHOOK_ID=${WH_MAIN_ID}
LOADTEST_DEDUP_WEBHOOK_ID=${WH_DEDUP_ID:-}
LOADTEST_CRED_ID=${CRED_ID}
LOADTEST_SYMBOL=${LOADTEST_SYMBOL}
EOF
  chmod 600 "${OUT_ENV}"
}

verify_ingest_token() {
  local token="$1"
  [[ -z "${token}" ]] && return 1
  local code
  code="$(ingest_live "${token}" "loadtest-setup-verify-$(date +%s)-${RANDOM}")"
  [[ "${code}" == "202" || "${code}" == "409" ]]
}

find_cred_by_label() {
  local label="$1"
  echo "${CREDS_JSON}" | jq -r --arg l "${label}" \
    '.data[] | select(.account_label == $l) | .id' | head -1
}

find_webhook_by_label() {
  local label="$1"
  echo "${WEBHOOKS_JSON}" | jq -r --arg l "${label}" \
    '.data[] | select(.label == $l) | .id' | head -1
}

ensure_webhook() {
  local label="$1" dedup="$2" rl_sec="$3"
  local -n out_token="$4"
  local -n out_id="$5"

  local existing_id
  existing_id="$(find_webhook_by_label "${label}")"
  if [[ -n "${existing_id}" ]]; then
    if [[ -n "${out_token}" ]] && verify_ingest_token "${out_token}"; then
      out_id="${existing_id}"
      echo "    reuse webhook ${label} (${existing_id})"
      return 0
    fi
    echo "webhook ${label} exists (${existing_id}) but token is missing or invalid" >&2
    echo "  delete it via dashboard/API or remove ${OUT_ENV} and re-run setup" >&2
    exit 1
  fi

  local wh_resp
  wh_resp="$(create_webhook "${label}" "${dedup}" "${rl_sec}")"
  out_token="$(echo "${wh_resp}" | jq -r '.data.token // empty')"
  out_id="$(echo "${wh_resp}" | jq -r '.data.id // empty')"
  if [[ -z "${out_token}" || -z "${out_id}" ]]; then
    echo "webhook create failed (${label}): $(echo "${wh_resp}" | jq -c '.')" >&2
    exit 1
  fi
  echo "    created webhook ${label} (${out_id})"
}

ingest_live() {
  local token="$1" comment="$2"
  "${CURL[@]}" -o /tmp/zb-loadtest-ingest.json -w '%{http_code}' \
    -X POST "${BASE_URL}/v1/webhook/${token}" \
    -H 'Content-Type: application/json' \
    -d "{\"action\":\"BUY\",\"symbol\":\"${LOADTEST_SYMBOL}\",\"lot\":1,\"comment\":\"${comment}\"}"
}

upgrade_plan() {
  local user_id="$1" plan="$2"
  json_put "/v1/admin/users/${user_id}/plan" "${ADMIN_TOKEN}" "{\"plan\":\"${plan}\"}"
}

echo "==> Admin login"
admin_login="$(json_post /v1/auth/login '' \
  "{\"email\":\"${ADMIN_EMAIL}\",\"password\":\"${ADMIN_PASSWORD}\"}")"
ADMIN_TOKEN="$(echo "${admin_login}" | jq -r '.data.token // empty')"
if [[ -z "${ADMIN_TOKEN}" ]]; then
  echo "admin login failed: $(echo "${admin_login}" | jq -c '.')" >&2
  exit 1
fi

echo "==> Disable market-hours enforcement (paper fills if used later)"
json_put /v1/admin/settings/market-hours-enforcement "${ADMIN_TOKEN}" '{"enabled":false}' >/dev/null || true

echo "==> Register or login load-test user (${LOADTEST_EMAIL})"
reg="$(json_post /v1/auth/register '' \
  "{\"email\":\"${LOADTEST_EMAIL}\",\"password\":\"${LOADTEST_PASSWORD}\"}")"
if echo "${reg}" | jq -e '.error' >/dev/null 2>&1; then
  echo "    register skipped: $(echo "${reg}" | jq -r '.error')"
fi

user_login="$(json_post /v1/auth/login '' \
  "{\"email\":\"${LOADTEST_EMAIL}\",\"password\":\"${LOADTEST_PASSWORD}\"}")"
USER_TOKEN="$(echo "${user_login}" | jq -r '.data.token // empty')"
USER_ID="$(echo "${user_login}" | jq -r '.data.id // empty')"
if [[ -z "${USER_TOKEN}" ]]; then
  echo "load-test user login failed: $(echo "${user_login}" | jq -c '.')" >&2
  exit 1
fi
if [[ -z "${USER_ID}" ]]; then
  me="$("${CURL[@]}" "${BASE_URL}/v1/me" -H "Authorization: Bearer ${USER_TOKEN}")"
  USER_ID="$(echo "${me}" | jq -r '.data.id // empty')"
fi

echo "==> Upgrade load-test user plan (pro_plus preferred; pro fallback)"
LOADTEST_PLAN="pro_plus"
plan_out="$(upgrade_plan "${USER_ID}" "pro_plus")"
if echo "${plan_out}" | jq -e '.error' >/dev/null 2>&1; then
  echo "    pro_plus failed ($(echo "${plan_out}" | jq -r '.error')) — trying pro"
  plan_out="$(upgrade_plan "${USER_ID}" "pro")"
  if echo "${plan_out}" | jq -e '.error' >/dev/null 2>&1; then
    echo "plan upgrade failed: $(echo "${plan_out}" | jq -c '.')" >&2
    exit 1
  fi
  LOADTEST_PLAN="pro"
fi
echo "    plan=${LOADTEST_PLAN}"

create_webhook() {
  local label="$1" dedup="$2" rl_sec="$3"
  local body
  body="$(jq -nc \
    --arg label "${label}" \
    --arg cred "${CRED_ID}" \
    --arg sym "${LOADTEST_SYMBOL}" \
    --argjson dedup "${dedup}" \
    --argjson rl "${rl_sec}" \
    '{label:$label,broker_cred_id:$cred,allowed_symbols:[$sym],lot_size:1,max_risk_pct:0,dedup_window_sec:$dedup,rate_limit_per_sec:$rl,rate_limit_per_min:0}')"
  json_post /v1/webhooks "${USER_TOKEN}" "${body}"
}

patch_webhook() {
  local webhook_id="$1" body="$2"
  json_put "/v1/webhooks/${webhook_id}" "${USER_TOKEN}" "${body}" >/dev/null
}

reset_ingest_webhook_limits() {
  local webhook_id="$1"
  [[ -z "${webhook_id}" ]] && return 0
  echo "    reset ingest limits on ${webhook_id} (explicit 0 disables 60/min default)"
  patch_webhook "${webhook_id}" '{"rate_limit_per_sec":0,"rate_limit_per_min":0,"dedup_window_sec":0}'
}

configure_dedup_webhook() {
  local webhook_id="$1"
  [[ -z "${webhook_id}" ]] && return 0
  echo "    configure dedup webhook ${webhook_id} (dedup_window_sec=60, rate limits off)"
  patch_webhook "${webhook_id}" '{"rate_limit_per_sec":0,"rate_limit_per_min":0,"dedup_window_sec":60}'
}

echo "==> Fetch existing credentials and webhooks"
CREDS_JSON="$(json_get /v1/credentials "${USER_TOKEN}")"
WEBHOOKS_JSON="$(json_get /v1/webhooks "${USER_TOKEN}")"

TOKEN_MAIN="${LOADTEST_WEBHOOK_TOKEN:-}"
TOKEN_DEDUP="${LOADTEST_DEDUP_WEBHOOK_TOKEN:-}"
TOKEN_RL1="${LOADTEST_RL_FREE_TOKEN:-}"
TOKEN_RL10="${LOADTEST_RL_PAID_TOKEN:-}"
WH_MAIN_ID="${LOADTEST_WEBHOOK_ID:-}"
WH_DEDUP_ID=""
WH_RL1_ID=""
WH_RL10_ID=""
CRED_ID="${LOADTEST_CRED_ID:-}"

QUICK_REUSE=0
if [[ -n "${TOKEN_MAIN}" ]] && verify_ingest_token "${TOKEN_MAIN}"; then
  QUICK_REUSE=1
  if [[ "${LOADTEST_PLAN}" == "pro_plus" ]]; then
    for label in loadtest-dedup loadtest-rl-1 loadtest-rl-10; do
      if [[ -z "$(find_webhook_by_label "${label}")" ]]; then
        echo "    missing webhook ${label} — continuing setup"
        QUICK_REUSE=0
        break
      fi
    done
    if [[ "${QUICK_REUSE}" == "1" && ( -z "${TOKEN_DEDUP}" || -z "${TOKEN_RL1}" || -z "${TOKEN_RL10}" ) ]]; then
      echo "    env.local missing dedicated webhook tokens — continuing setup"
      QUICK_REUSE=0
    fi
  fi
fi

if [[ "${QUICK_REUSE}" == "1" ]]; then
  echo "==> Existing load-test setup verified — refreshing env.local"
  [[ -z "${CRED_ID}" ]] && CRED_ID="$(find_cred_by_label "loadtest")"
  [[ -z "${WH_MAIN_ID}" ]] && WH_MAIN_ID="$(find_webhook_by_label "loadtest-ingest")"
  if [[ "${LOADTEST_PLAN}" == "pro_plus" ]]; then
    WH_DEDUP_ID="$(find_webhook_by_label "loadtest-dedup")"
    configure_dedup_webhook "${WH_DEDUP_ID}"
  else
    TOKEN_DEDUP="${TOKEN_MAIN}"
    TOKEN_RL1="${TOKEN_MAIN}"
    TOKEN_RL10="${TOKEN_MAIN}"
  fi
  reset_ingest_webhook_limits "${WH_MAIN_ID}"
  write_env_file
  echo
  echo "Load-test webhooks ready (plan=${LOADTEST_PLAN}, reused existing tokens)."
  echo "  env file=${OUT_ENV}"
  echo "  user=${LOADTEST_EMAIL}"
  echo "  main webhook=${WH_MAIN_ID}"
  exit 0
fi

echo "==> Find or create zerodha live credential (shared by all load-test webhooks)"
CRED_ID="$(find_cred_by_label "loadtest")"
if [[ -z "${CRED_ID}" ]]; then
  cred="$(json_post /v1/credentials "${USER_TOKEN}" \
    '{"broker_type":"zerodha","account_label":"loadtest","account_mode":"live","raw_creds":"api_key:loadtest_secret:loadtest_token","exchange":"NSE","product":"MIS","algo_id":"LOADTEST"}')"
  CRED_ID="$(echo "${cred}" | jq -r '.data.id // empty')"
  if [[ -z "${CRED_ID}" ]]; then
    echo "credential create failed: $(echo "${cred}" | jq -c '.')" >&2
    exit 1
  fi
  echo "    created credential loadtest (${CRED_ID})"
else
  echo "    reuse credential loadtest (${CRED_ID})"
fi

echo "==> Find or create webhooks"
ensure_webhook "loadtest-ingest" 0 0 TOKEN_MAIN WH_MAIN_ID
reset_ingest_webhook_limits "${WH_MAIN_ID}"

if [[ "${LOADTEST_PLAN}" == "pro_plus" ]]; then
  ensure_webhook "loadtest-dedup" 60 0 TOKEN_DEDUP WH_DEDUP_ID
  configure_dedup_webhook "${WH_DEDUP_ID}"
  ensure_webhook "loadtest-rl-1" 0 1 TOKEN_RL1 WH_RL1_ID
  ensure_webhook "loadtest-rl-10" 0 10 TOKEN_RL10 WH_RL10_ID
else
  echo "    pro plan: only one live webhook — dedup/rate-limit scenarios share main token"
  echo "    (run migrations/046_expand_plan_tiers.sql for full multi-webhook setup)"
  TOKEN_DEDUP="${TOKEN_MAIN}"
  TOKEN_RL1="${TOKEN_MAIN}"
  TOKEN_RL10="${TOKEN_MAIN}"
fi

if [[ -z "${TOKEN_MAIN}" ]]; then
  echo "main webhook missing after setup" >&2
  exit 1
fi

echo "==> Verify ingest on main webhook"
ingest_code="$(ingest_live "${TOKEN_MAIN}" "loadtest-setup")"
if [[ "${ingest_code}" != "202" ]]; then
  echo "setup ingest failed HTTP ${ingest_code}: $(cat /tmp/zb-loadtest-ingest.json)" >&2
  exit 1
fi

write_env_file

echo
echo "Load-test webhooks ready (plan=${LOADTEST_PLAN})."
echo "  env file=${OUT_ENV}"
echo "  user=${LOADTEST_EMAIL}"
echo "  main webhook=${WH_MAIN_ID}"
[[ -n "${WH_DEDUP_ID}" ]] && echo "  dedup webhook=${WH_DEDUP_ID}"
[[ -n "${WH_RL1_ID}" ]] && echo "  rate-1 webhook=${WH_RL1_ID}"
[[ -n "${WH_RL10_ID}" ]] && echo "  rate-10 webhook=${WH_RL10_ID}"
echo
echo "Run:"
echo "  ./deploy/loadtest/run-loadtest.sh smoke"
echo "  ./deploy/loadtest/run-loadtest.sh target"
echo "  ./deploy/loadtest/run-loadtest.sh ramp"
echo "  ./deploy/loadtest/run-loadtest.sh dedup"
echo "  ./deploy/loadtest/run-loadtest.sh bracket"
echo "  ./deploy/loadtest/run-loadtest.sh soak"
echo "  ./deploy/loadtest/run-loadtest.sh rate-limit-free"
echo "  ./deploy/loadtest/run-loadtest.sh rate-limit-paid"
