package store

import "time"

// ── Users ─────────────────────────────────────────────────────────────────────

type User struct {
	ID                   string     `db:"id"            json:"id"`
	Email                string     `db:"email"         json:"email"`
	PasswordHash         string     `db:"password_hash" json:"-"`
	Plan                 string     `db:"plan"          json:"plan"`         // free | individual | household
	Role                 string     `db:"role"          json:"role"`         // user | admin
	Status               string     `db:"status"        json:"status"`       // active | suspended
	OrgsEnabled          bool       `db:"orgs_enabled"  json:"orgs_enabled"` // platform admin enables org creation
	EarlyBirdLive        bool       `db:"early_bird_live" json:"early_bird_live"`
	LiveOrdersUsed       int        `db:"live_orders_used"  json:"live_orders_used"`
	EmailVerifiedAt      *time.Time `db:"email_verified_at" json:"email_verified_at,omitempty"`
	StripeCustomerID     string     `db:"stripe_customer_id"     json:"stripe_customer_id,omitempty"`
	StripeSubscriptionID string     `db:"stripe_subscription_id" json:"stripe_subscription_id,omitempty"`
	BillingSource        string     `db:"billing_source"         json:"billing_source"` // free | stripe | admin
	TelegramChatID       string     `db:"telegram_chat_id"       json:"telegram_chat_id,omitempty"`
	CreatedAt            time.Time  `db:"created_at"        json:"created_at"`
}

// EmailVerified reports whether the user completed email verification.
func (u *User) EmailVerified() bool {
	return u != nil && u.EmailVerifiedAt != nil
}

// EmailVerification is a pending one-time verify link (raw token never stored).
type EmailVerification struct {
	ID         string     `db:"id"`
	UserID     string     `db:"user_id"`
	TokenHash  string     `db:"token_hash"`
	ExpiresAt  time.Time  `db:"expires_at"`
	ConsumedAt *time.Time `db:"consumed_at"`
	CreatedAt  time.Time  `db:"created_at"`
}

// Organization is a household workspace.
type Organization struct {
	ID          string    `db:"id"            json:"id"`
	Name        string    `db:"name"          json:"name"`
	Slug        string    `db:"slug"          json:"slug"`
	OwnerUserID string    `db:"owner_user_id" json:"owner_user_id"`
	SeatLimit   int       `db:"seat_limit"    json:"seat_limit"`
	Status      string    `db:"status"        json:"status"` // active | suspended
	CreatedAt   time.Time `db:"created_at"    json:"created_at"`
}

// OrgMember links a user to an organization with an org role.
type OrgMember struct {
	ID       string    `db:"id"        json:"id"`
	OrgID    string    `db:"org_id"    json:"org_id"`
	UserID   string    `db:"user_id"   json:"user_id"`
	Role     string    `db:"role"      json:"role"`   // owner | admin | member | viewer
	Status   string    `db:"status"    json:"status"` // active | suspended
	JoinedAt time.Time `db:"joined_at" json:"joined_at"`
}

// OrgDetail is returned from org read APIs.
type OrgDetail struct {
	Organization
	MemberCount int    `json:"member_count"`
	SeatsUsed   int    `json:"seats_used"`
	YourRole    string `json:"your_role"`
}

// OrgMemberProfile is a member row with public user fields.
type OrgMemberProfile struct {
	OrgMember
	Email string `json:"email"`
}

// OrgInvite is a pending or historical invite to join an organization.
type OrgInvite struct {
	ID         string     `db:"id"          json:"id"`
	OrgID      string     `db:"org_id"      json:"org_id"`
	Email      string     `db:"email"       json:"email"`
	Role       string     `db:"role"        json:"role"`
	TokenHash  string     `db:"token_hash"  json:"-"`
	ExpiresAt  time.Time  `db:"expires_at"  json:"expires_at"`
	AcceptedAt *time.Time `db:"accepted_at" json:"accepted_at,omitempty"`
	RevokedAt  *time.Time `db:"revoked_at"  json:"revoked_at,omitempty"`
	InvitedBy  string     `db:"invited_by"  json:"invited_by"`
	CreatedAt  time.Time  `db:"created_at"  json:"created_at"`
}

// PlatformInvite is a one-time registration invite generated by a platform admin.
type PlatformInvite struct {
	ID        string     `db:"id"         json:"id"`
	TokenHash string     `db:"token_hash" json:"-"`
	Email     string     `db:"email"      json:"email,omitempty"`
	Note      string     `db:"note"       json:"note,omitempty"`
	UsedAt    *time.Time `db:"used_at"    json:"used_at,omitempty"`
	UsedBy    string     `db:"used_by"    json:"used_by,omitempty"`
	ExpiresAt time.Time  `db:"expires_at" json:"expires_at"`
	RevokedAt *time.Time `db:"revoked_at" json:"revoked_at,omitempty"`
	CreatedBy string     `db:"created_by" json:"created_by"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
}

// PlatformInviteRow is returned by the admin list endpoint (includes used-by email).
type PlatformInviteRow struct {
	PlatformInvite
	UsedByEmail string `json:"used_by_email,omitempty"`
}

// OrgInvitePreview is returned from public invite preview (no secrets).
type OrgInvitePreview struct {
	OrgName   string    `json:"org_name"`
	Email     string    `json:"email"`
	Role      string    `json:"role"`
	ExpiresAt time.Time `json:"expires_at"`
}

// OrgUsage summarizes org resource consumption.
type OrgUsage struct {
	SeatLimit              int  `json:"seat_limit"`
	SeatsUsed              int  `json:"seats_used"`
	MemberCount            int  `json:"member_count"`
	PendingInvites         int  `json:"pending_invites"`
	WebhookCount           int  `json:"webhook_count"`
	CredentialCount        int  `json:"credential_count"`
	TradesLast30Days       int  `json:"trades_last_30_days"`
	TradesLast24Hours      int  `json:"trades_last_24_hours"`
	OrdersPerSec           *int `json:"orders_per_sec"`          // nil = unlimited org user aggregate
	OrdersPerSecPerUser    int  `json:"orders_per_sec_per_user"` // 0 = unlimited
	BrokerCredOrdersPerSec int  `json:"broker_cred_orders_per_sec"`
	MaxWebhooks            int  `json:"max_webhooks"`
	MaxBrokerCreds         int  `json:"max_broker_creds"`
}

// OrgAuditEntry is a single org governance audit row.
type OrgAuditEntry struct {
	ID           string    `json:"id"`
	OrgID        string    `json:"org_id"`
	ActorUserID  string    `json:"actor_user_id"`
	Action       string    `json:"action"`
	TargetUserID string    `json:"target_user_id,omitempty"`
	Metadata     string    `json:"metadata,omitempty"`
	CreatedAt    time.Time `json:"created_at"`
}

// AdminOrgFilter filters platform admin org directory queries.
type AdminOrgFilter struct {
	Status string
	Name   string
	Page   int
	Limit  int
}

// AdminOrgSummary is an org row for platform admin list/detail.
type AdminOrgSummary struct {
	Organization
	MemberCount     int `json:"member_count"`
	WebhookCount    int `json:"webhook_count"`
	CredentialCount int `json:"credential_count"`
	SeatsUsed       int `json:"seats_used"`
}

// AdminOrgListResult is a paginated admin org directory.
type AdminOrgListResult struct {
	Orgs       []*AdminOrgSummary `json:"orgs"`
	Total      int                `json:"total"`
	Page       int                `json:"page"`
	Limit      int                `json:"limit"`
	TotalPages int                `json:"total_pages"`
}

// UserWithCounts is an admin view with resource aggregates.
type UserWithCounts struct {
	User
	WebhookCount int `json:"webhook_count"`
	BrokerCount  int `json:"broker_count"`
}

// AdminUserListResult is a paginated admin user directory.
type AdminUserListResult struct {
	Users      []*UserWithCounts `json:"users"`
	Total      int               `json:"total"`
	Page       int               `json:"page"`
	Limit      int               `json:"limit"`
	TotalPages int               `json:"total_pages"`
}

// ── Webhooks ──────────────────────────────────────────────────────────────────

type Webhook struct {
	ID        string  `db:"id"               json:"id"`
	UserID    string  `db:"user_id"          json:"user_id"`
	OrgID     *string `db:"org_id"           json:"org_id,omitempty"`
	CreatedBy string  `db:"created_by"       json:"created_by"`
	TokenHash string  `db:"token_hash"       json:"-"`
	RawToken  string  `db:"-"                json:"token,omitempty"`
	Label     string  `db:"label"            json:"label"`
	Status    string  `db:"status"           json:"status"` // active | paused
	// Exactly one of BrokerCredID / PaperAccountID is set — see
	// migrations/036_webhook_paper_destination.sql's CHECK constraint.
	BrokerCredID     *string   `db:"broker_cred_id"   json:"broker_cred_id,omitempty"`
	PaperAccountID   *string   `db:"paper_account_id" json:"paper_account_id,omitempty"`
	Symbol           string    `db:"symbol"           json:"symbol"`
	LotSize          float64   `db:"lot_size"         json:"lot_size"`
	MaxRiskPct       float64   `db:"max_risk_pct"     json:"max_risk_pct"`
	SLPoints         int       `db:"sl_points"        json:"sl_points"`
	TPPoints         int       `db:"tp_points"        json:"tp_points"`
	DefaultOrderType string    `db:"default_order_type" json:"default_order_type"`
	CreatedAt        time.Time `db:"created_at"       json:"created_at"`

	// Phase 1 guards (all plans)
	AllowedActions []string `db:"allowed_actions" json:"allowed_actions"`
	AllowedSymbols []string `db:"allowed_symbols" json:"allowed_symbols"`
	MaxLotSize     float64  `db:"max_lot_size"    json:"max_lot_size"`

	// Phase 2 guards (pro+ to configure)
	RateLimitPerSec int              `db:"rate_limit_per_sec" json:"rate_limit_per_sec"`
	RateLimitPerMin int              `db:"rate_limit_per_min" json:"rate_limit_per_min"`
	DedupWindowSec  int              `db:"dedup_window_sec"   json:"dedup_window_sec"`
	Timezone        string           `db:"timezone"           json:"timezone"`
	TradingHours    *TradingSchedule `db:"trading_hours"      json:"trading_hours"`
	RequiredComment string           `db:"required_comment"   json:"required_comment"`

	// Set to true when the system paused this webhook on a plan downgrade.
	AutoPaused bool `db:"auto_paused" json:"auto_paused"`
	// Set to true when the system paused this webhook because an admin
	// disabled the Zerodha execution mode its credential uses. Distinct from
	// AutoPaused so resuming one cause doesn't accidentally clear the other.
	AdminDisabled bool `db:"admin_disabled" json:"admin_disabled"`
}

// ── Refresh tokens ────────────────────────────────────────────────────────────

type RefreshToken struct {
	ID        string     `db:"id"`
	UserID    string     `db:"user_id"`
	TokenHash string     `db:"token_hash"`
	ExpiresAt time.Time  `db:"expires_at"`
	CreatedAt time.Time  `db:"created_at"`
	RevokedAt *time.Time `db:"revoked_at"`
}

// ── Broker Credentials ────────────────────────────────────────────────────────

type BrokerCredential struct {
	ID               string     `db:"id"               json:"id"`
	UserID           string     `db:"user_id"          json:"user_id"`
	OrgID            *string    `db:"org_id"           json:"org_id,omitempty"`
	CreatedBy        string     `db:"created_by"       json:"created_by"`
	BrokerType       string     `db:"broker_type"      json:"broker_type"`    // mt5_cloud | zerodha | angel | dhan
	ExecutionMode    string     `db:"execution_mode"   json:"execution_mode"` // direct_api | user_api_oauth | publisher
	EncryptedCreds   string     `db:"encrypted_creds"  json:"-"`
	AccountLabel     string     `db:"account_label"    json:"account_label"`
	AccountMode      string     `db:"account_mode"     json:"account_mode"` // demo | live — selects the broker's own sandbox vs production API; see plan.AccountDemo/AccountLive. Distinct from domain.DestinationKindPaperTrading, which never reaches broker code at all.
	Exchange         string     `db:"exchange"         json:"exchange"`     // NSE | BSE (Indian brokers)
	Product          string     `db:"product"          json:"product"`      // MIS | CNC | NRML
	AlgoID           string     `db:"algo_id"            json:"algo_id,omitempty"`
	OrderType        string     `db:"order_type"         json:"order_type"`        // MARKET | LIMIT
	MarketProtection float64    `db:"market_protection"  json:"market_protection"` // protection % for MARKET; slippage % for LIMIT
	ConnectedAt      *time.Time `db:"connected_at"       json:"connected_at,omitempty"`
	Status           string     `db:"status"             json:"status"`      // active | paused
	AutoPaused       bool       `db:"auto_paused"        json:"auto_paused"` // true = paused by system on plan downgrade
	// AdminDisabled is true when the system paused this credential because an
	// admin disabled its Zerodha execution mode (OAuth or Publisher)
	// platform-wide. Distinct from AutoPaused so resuming one cause doesn't
	// accidentally clear the other.
	AdminDisabled bool `db:"admin_disabled" json:"admin_disabled"`
}

// ── Notifications ─────────────────────────────────────────────────────────────

type Notification struct {
	ID        string     `db:"id"         json:"id"`
	UserID    string     `db:"user_id"    json:"user_id"`
	Type      string     `db:"type"       json:"type"`
	Title     string     `db:"title"      json:"title"`
	Body      string     `db:"body"       json:"body"`
	TradeID   string     `db:"trade_id"   json:"trade_id,omitempty"`
	ReadAt    *time.Time `db:"read_at"    json:"read_at,omitempty"`
	CreatedAt time.Time  `db:"created_at" json:"created_at"`
}

// ── Trades ────────────────────────────────────────────────────────────────────

type Trade struct {
	ID           string     `db:"id"            json:"id"`
	UserID       string     `db:"user_id"       json:"user_id,omitempty"`
	WebhookID    string     `db:"webhook_id"    json:"webhook_id"`
	WebhookLabel string     `db:"webhook_label" json:"webhook_label,omitempty"`
	Signal       string     `db:"signal"        json:"signal"` // BUY | SELL | CLOSE
	Symbol       string     `db:"symbol"        json:"symbol"`
	LotSize      float64    `db:"lot_size"      json:"lot_size"`
	BrokerOrder  string     `db:"broker_order"  json:"broker_order"`
	SignalKey    string     `db:"signal_key"    json:"signal_key,omitempty"`
	Comment      string     `db:"comment"       json:"comment,omitempty"`
	AlgoID       string     `db:"algo_id"       json:"algo_id,omitempty"`
	Status       string     `db:"status"        json:"status"` // queued | submitted | filled | rejected | cancelled
	FillPrice    float64    `db:"fill_price"    json:"fill_price"`
	OrderType    string     `db:"order_type"    json:"order_type"` // MARKET | LIMIT | BRACKET (entry type)
	Product      string     `db:"product"       json:"product"`    // MIS | CNC | NRML
	SLPrice      *float64   `db:"sl_price"      json:"sl_price,omitempty"`
	TPPrice      *float64   `db:"tp_price"      json:"tp_price,omitempty"`
	Error        string     `db:"error"         json:"error,omitempty"`
	ErrorCode    string     `db:"error_code"    json:"error_code,omitempty"`
	CancelledAt  *time.Time `db:"cancelled_at"  json:"cancelled_at,omitempty"`
	CancelError  string     `db:"cancel_error"  json:"cancel_error,omitempty"`
	CreatedAt    time.Time  `db:"created_at"    json:"created_at"`
	// BrokerRespondedAt is set once when the worker finishes broker/paper
	// delivery (FinalizeTrade). Fill poll and other later updates must not
	// change it — used for avg latency (created_at → broker_responded_at).
	BrokerRespondedAt *time.Time `db:"broker_responded_at" json:"broker_responded_at,omitempty"`
	// Populated via LEFT JOIN with publisher_orders when listing by webhook; nil for non-publisher trades.
	PublisherOrderExpiresAt *time.Time `db:"-" json:"publisher_order_expires_at,omitempty"`
}

// ── Paper Trading (broker-free simulation; see domain.DestinationKindPaperTrading) ───

// MarketProfile is an admin-configurable asset-class definition (Phase 7) —
// paper_accounts.market_profile references its `code`. trading_days uses
// the same TradingSchedule shape as webhooks (nil/empty = 24/7).
type MarketProfile struct {
	ID           string           `db:"id"            json:"id"`
	Code         string           `db:"code"          json:"code"`
	Name         string           `db:"name"          json:"name"`
	BaseCurrency string           `db:"base_currency" json:"base_currency"`
	Timezone     string           `db:"timezone"      json:"timezone"`
	TradingDays  *TradingSchedule `db:"trading_days"  json:"trading_days"`
	Active       bool             `db:"active"        json:"active"`
	// SlippageBps/FeeBps model Paper Trading execution friction — see
	// migration 042. SlippageBps worsens the simulated fill price;
	// FeeBps is a combined brokerage+taxes+charges estimate applied to
	// notional. Both 0 by default (no friction) until an admin opts in.
	SlippageBps float64   `db:"slippage_bps"  json:"slippage_bps"`
	FeeBps      float64   `db:"fee_bps"        json:"fee_bps"`
	CreatedAt   time.Time `db:"created_at"    json:"created_at"`
	UpdatedAt   time.Time `db:"updated_at"    json:"updated_at"`
}

// Instrument is a single tradable symbol within a MarketProfile — the
// symbol master table (Phase 7). Paper orders are validated against this:
// unknown/inactive symbol, non-tick-size price, or non-lot-size quantity
// are all rejected before reaching the fill engine.
type Instrument struct {
	ID                string    `db:"id"                  json:"id"`
	MarketProfileCode string    `db:"market_profile_code" json:"market_profile_code"`
	Exchange          string    `db:"exchange"            json:"exchange"`
	Symbol            string    `db:"symbol"              json:"symbol"`
	Name              string    `db:"name"                json:"name"`
	InstrumentType    string    `db:"instrument_type"     json:"instrument_type"` // EQUITY | INDEX | FUTURES | OPTIONS
	TickSize          float64   `db:"tick_size"           json:"tick_size"`
	LotSize           float64   `db:"lot_size"            json:"lot_size"`
	Active            bool      `db:"active"              json:"active"`
	CreatedAt         time.Time `db:"created_at"          json:"created_at"`
	UpdatedAt         time.Time `db:"updated_at"          json:"updated_at"`
}

// SymbolRequest is a user's ask to add a symbol to a market profile's
// instrument master, surfaced from the "unknown or inactive symbol"
// paper-trading rejection. Status: pending | accepted | rejected | resolved
// — resolved is set automatically when a matching instrument is created,
// not by direct admin action (see store.ResolveSymbolRequestsByInstrument).
type SymbolRequest struct {
	ID                   string     `db:"id"                      json:"id"`
	UserID               string     `db:"user_id"                 json:"user_id"`
	MarketProfileCode    string     `db:"market_profile_code"     json:"market_profile_code"`
	Exchange             string     `db:"exchange"                json:"exchange"`
	Symbol               string     `db:"symbol"                  json:"symbol"`
	Reason               string     `db:"reason"                  json:"reason"`
	Status               string     `db:"status"                  json:"status"`
	AdminNote            string     `db:"admin_note"               json:"admin_note"`
	ReviewedBy           *string    `db:"reviewed_by"              json:"reviewed_by,omitempty"`
	ReviewedAt           *time.Time `db:"reviewed_at"              json:"reviewed_at,omitempty"`
	ResolvedInstrumentID *string    `db:"resolved_instrument_id"   json:"resolved_instrument_id,omitempty"`
	ResolvedAt           *time.Time `db:"resolved_at"              json:"resolved_at,omitempty"`
	CreatedAt            time.Time  `db:"created_at"               json:"created_at"`
	UpdatedAt            time.Time  `db:"updated_at"               json:"updated_at"`
}

type PaperAccount struct {
	ID              string    `db:"id"               json:"id"`
	UserID          string    `db:"user_id"          json:"user_id"`
	Label           string    `db:"label"            json:"label"`
	MarketProfile   string    `db:"market_profile"   json:"market_profile"` // references market_profiles.code
	BaseCurrency    string    `db:"base_currency"     json:"base_currency"`
	StartingBalance float64   `db:"starting_balance" json:"starting_balance"`
	CashBalance     float64   `db:"cash_balance"     json:"cash_balance"`
	Exchange        string    `db:"exchange"         json:"exchange"`        // NSE | BSE
	DefaultProduct  string    `db:"default_product"  json:"default_product"` // MIS | CNC | NRML
	Status          string    `db:"status"           json:"status"`          // active | paused | closed
	CreatedAt       time.Time `db:"created_at"       json:"created_at"`
	UpdatedAt       time.Time `db:"updated_at"       json:"updated_at"`
}

type PaperOrder struct {
	ID             string    `db:"id"                json:"id"`
	UserID         string    `db:"user_id"           json:"user_id"`
	PaperAccountID string    `db:"paper_account_id"  json:"paper_account_id"`
	WebhookID      *string   `db:"webhook_id"        json:"webhook_id,omitempty"`
	SignalID       string    `db:"signal_id"         json:"signal_id,omitempty"`
	Symbol         string    `db:"symbol"            json:"symbol"`
	Exchange       string    `db:"exchange"          json:"exchange"`
	Side           string    `db:"side"              json:"side"`       // BUY | SELL | CLOSE
	OrderType      string    `db:"order_type"        json:"order_type"` // MARKET | LIMIT
	Product        string    `db:"product"           json:"product"`
	Quantity       float64   `db:"quantity"          json:"quantity"`
	RequestedPrice *float64  `db:"requested_price"   json:"requested_price,omitempty"`
	FillPrice      *float64  `db:"fill_price"        json:"fill_price,omitempty"`
	Status         string    `db:"status"            json:"status"` // RECEIVED | VALIDATED | FILLED | REJECTED | CANCELLED
	Reason         string    `db:"reason"            json:"reason,omitempty"`
	RawSignal      []byte    `db:"raw_signal"        json:"raw_signal,omitempty"`
	CreatedAt      time.Time `db:"created_at"        json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at"        json:"updated_at"`
}

// PaperPosition is signed: Quantity > 0 long, < 0 short, 0 closed.
type PaperPosition struct {
	ID             string    `db:"id"               json:"id"`
	UserID         string    `db:"user_id"          json:"user_id"`
	PaperAccountID string    `db:"paper_account_id" json:"paper_account_id"`
	Symbol         string    `db:"symbol"           json:"symbol"`
	Exchange       string    `db:"exchange"         json:"exchange"`
	Product        string    `db:"product"          json:"product"`
	Quantity       float64   `db:"quantity"         json:"quantity"`
	AvgEntryPrice  float64   `db:"avg_entry_price"  json:"avg_entry_price"`
	LastPrice      float64   `db:"last_price"       json:"last_price"`
	UnrealizedPnL  float64   `db:"unrealized_pnl"   json:"unrealized_pnl"`
	CreatedAt      time.Time `db:"created_at"       json:"created_at"`
	UpdatedAt      time.Time `db:"updated_at"       json:"updated_at"`
}

// PaperTrade is the immutable executed-fill history for a paper account.
type PaperTrade struct {
	ID             string    `db:"id"               json:"id"`
	UserID         string    `db:"user_id"          json:"user_id"`
	PaperAccountID string    `db:"paper_account_id" json:"paper_account_id"`
	OrderID        string    `db:"order_id"         json:"order_id"`
	Symbol         string    `db:"symbol"           json:"symbol"`
	Exchange       string    `db:"exchange"         json:"exchange"`
	Side           string    `db:"side"             json:"side"` // BUY | SELL
	Quantity       float64   `db:"quantity"         json:"quantity"`
	Price          float64   `db:"price"            json:"price"`
	RealizedPnL    float64   `db:"realized_pnl"     json:"realized_pnl"`
	Fees           float64   `db:"fees"             json:"fees"`
	CreatedAt      time.Time `db:"created_at"       json:"created_at"`
}

// PaperAccountSnapshot is a point-in-time equity/P&L snapshot, written by the
// Phase 6 mark-to-market updater.
type PaperAccountSnapshot struct {
	ID             string    `db:"id"               json:"id"`
	UserID         string    `db:"user_id"          json:"user_id"`
	PaperAccountID string    `db:"paper_account_id" json:"paper_account_id"`
	Equity         float64   `db:"equity"           json:"equity"`
	CashBalance    float64   `db:"cash_balance"     json:"cash_balance"`
	UnrealizedPnL  float64   `db:"unrealized_pnl"   json:"unrealized_pnl"`
	RealizedPnL    float64   `db:"realized_pnl"     json:"realized_pnl"`
	CreatedAt      time.Time `db:"created_at"       json:"created_at"`
}

// FyersConnection is the single platform-wide FYERS OAuth connection used
// only for market-data quotes (never order placement). Tokens/PIN are
// stored encrypted (internal/platform/crypto) — never returned in plaintext
// via the API.
type FyersConnection struct {
	ID                    string     `db:"id"                       json:"id"`
	EncryptedAccessToken  string     `db:"encrypted_access_token"   json:"-"`
	EncryptedRefreshToken string     `db:"encrypted_refresh_token"  json:"-"`
	EncryptedPIN          string     `db:"encrypted_pin"            json:"-"`
	AccessTokenExpiresAt  *time.Time `db:"access_token_expires_at"  json:"access_token_expires_at,omitempty"`
	RefreshTokenExpiresAt *time.Time `db:"refresh_token_expires_at" json:"refresh_token_expires_at,omitempty"`
	ConnectedBy           *string    `db:"connected_by"             json:"connected_by,omitempty"`
	ConnectedAt           *time.Time `db:"connected_at"              json:"connected_at,omitempty"`
	UpdatedAt             time.Time  `db:"updated_at"               json:"updated_at"`
}

// ── Publisher Orders ──────────────────────────────────────────────────────────

type PublisherOrder struct {
	ID                string  `db:"id"                   json:"id"`
	UserID            string  `db:"user_id"              json:"user_id"`
	CredentialID      string  `db:"credential_id"        json:"credential_id"`
	WebhookID         *string `db:"webhook_id"           json:"webhook_id,omitempty"`
	TradeID           *string `db:"trade_id"             json:"trade_id,omitempty"`
	Broker            string  `db:"broker"               json:"broker"`
	ExecutionMode     string  `db:"execution_mode"       json:"execution_mode"`
	BasketPayloadJSON []byte  `db:"basket_payload_json"  json:"-"`
	BasketPayloadHash string  `db:"basket_payload_hash"  json:"basket_payload_hash"`
	// status: created | awaiting_confirmation | user_returned | user_cancelled | expired
	Status           string     `db:"status"               json:"status"`
	CallbackStatus   *string    `db:"callback_status"      json:"callback_status,omitempty"`
	KiteRequestToken *string    `db:"kite_request_token"   json:"kite_request_token,omitempty"`
	SignedState      string     `db:"signed_state"         json:"-"`
	RedirectedAt     *time.Time `db:"redirected_at"        json:"redirected_at,omitempty"`
	CallbackAt       *time.Time `db:"callback_at"          json:"callback_at,omitempty"`
	ExpiresAt        time.Time  `db:"expires_at"           json:"expires_at"`
	CreatedAt        time.Time  `db:"created_at"           json:"created_at"`
	UpdatedAt        time.Time  `db:"updated_at"           json:"updated_at"`
}

type PublisherOrderEvent struct {
	ID               string    `db:"id"                  json:"id"`
	PublisherOrderID string    `db:"publisher_order_id"  json:"publisher_order_id"`
	EventType        string    `db:"event_type"          json:"event_type"`
	EventPayload     []byte    `db:"event_payload"       json:"-"`
	CreatedAt        time.Time `db:"created_at"          json:"created_at"`
}

// ── Webhook signal payload (inbound from TradingView / script) ────────────────

type SignalPayload struct {
	Action    string  `json:"action"`           // BUY | SELL | CLOSE
	Symbol    string  `json:"symbol,omitempty"` // overrides webhook default
	Lot       float64 `json:"lot,omitempty"`    // overrides webhook default
	SLPts     int     `json:"sl_pts,omitempty"`
	TPPts     int     `json:"tp_pts,omitempty"`
	Price     float64 `json:"price,omitempty"` // explicit LIMIT entry price; 0 = broker fetches LTP
	Comment   string  `json:"comment,omitempty"`
	Product   string  `json:"product,omitempty"`    // MIS | CNC | NRML — required when broker credential enables multiple products
	OrderType string  `json:"order_type,omitempty"` // MARKET | LIMIT — optional; if present, must match the webhook's configured default_order_type (see guard.ValidateIngest)
}

// PaperSignalPayload is the inbound wire format for paper-destination
// webhooks only (live-broker webhooks keep SignalPayload's flat shape
// unchanged). Typed payloads declare Type: ORDER_SIGNAL places or closes a
// paper order; PRICE_UPDATE marks a symbol's last price on any open position
// with no order/trade/cash effect. When Type is omitted, the flat SignalPayload
// shape (action, lot, …) is accepted for compatibility with live webhook scripts.
type PaperSignalPayload struct {
	Comment   string  `json:"comment"`
	Type      string  `json:"type"` // ORDER_SIGNAL | PRICE_UPDATE
	Symbol    string  `json:"symbol"`
	Action    string  `json:"action,omitempty"`     // ORDER_SIGNAL only: BUY | SELL | CLOSE
	Quantity  float64 `json:"quantity,omitempty"`   // ORDER_SIGNAL only (preferred)
	Lot       float64 `json:"lot,omitempty"`        // ORDER_SIGNAL only (legacy alias)
	Product   string  `json:"product,omitempty"`    // ORDER_SIGNAL only: MIS | CNC | NRML
	OrderType string  `json:"order_type,omitempty"` // MARKET | LIMIT — optional; if present, must match the webhook's configured default_order_type (see guard.ValidateIngest). Paper fills always use the webhook's configured type, same as the legacy shape.
	Price     float64 `json:"price,omitempty"`      // order price (ORDER_SIGNAL) or mark price (PRICE_UPDATE)
}
